---

- name: CentOS | SYSTEM | install epel-release
  yum: name=epel-release state=present
  tags: install epel-release

- name: CentOS | PRITUNL | download 
  get_url: url={{ pritunl_url }} dest=/tmp mode=0440
  tags: get_pritunl

- name: CentOS | PRITUNL | install
  yum: name=/tmp/{{ pritunl_pkg }} state=present
  tags: install_pritunl

- name: CentOS | PRITUNL | start service
  service: name=pritunl state=started
  tags: start_pritunl

- name: CentOS | PRITUNL | enable service
  service: name=pritunl enabled=yes
  tags: enable_pritunl